version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Installing Maven...
      - apt-get install -y maven
      - mvn -version
  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`      
artifacts:
  files:
    - target/datarest-spring-boot-expl.jar
    - appspec.yml
  discard-paths: yes